version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_up
    ports:
      - 3306:3306
    volumes:
      - db-volume:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80

  node:
    image: node:10-jessie-slim
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command:
      - /bin/sh
      - -c
      - |
        yarn
        yarn watch-poll

  composer:
    image: composer:1.8.3
    volumes:
      - .:/app
    command: install --ignore-platform-reqs

volumes:
  db-volume: