version: '3'

services:
  web:
    build:
      context: .
      dockerfile: .docker/web/Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_up
    ports:
      - 3306:3306
    volumes:
      - db-volume:/var/lib/mysql

  node:
    image: node:10-jessie-slim
    user: node
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
    volumes:
      - ./:/home/node/app
    expose:
      - 80
    depends_on:
      - web
    command:
      - /bin/sh
      - -c
      - |
        yarn
        yarn watch-poll

  composer:
    image: composer:1.8.3
    volumes:
      - .:/app
    depends_on:
      - web
    command: install --ignore-platform-reqs --no-scripts

volumes:
  db-volume: